type Guest {
  code: String!
  name: String!
  surveyRsvp: Int
  attendanceCount: Int
}

type Query {
  guests: [Guest]
  surveys: [SurveyResponse]
}

type SurveyResponse {
    name: String!
    value: Int!
    timestamp: String!
}