type Guest {
  id: ID!
  name: String!
  address: String
  city: String
  state: String
  zipcode: String
  phone: String
  surveyRsvp: Int
  attendanceCount: Int
  email: String
}

type Query {
  guests: [Guest]
}
